#!/bin/bash -x

set -euo pipefail
IFS=$'\n\t'

rm -rf /tmp/Dist-Zilla-Plugin-CommentOut

cpanm -n Dist::Zilla


git clone --depth 2 https://github.com/plicease/Dist-Zilla-Plugin-CommentOut.git /tmp/Dist-Zilla-Plugin-CommentOut
cd /tmp/Dist-Zilla-Plugin-CommentOut
dzil authordeps --missing | cpanm -n
dzil listdeps   --missing | cpanm -n
dzil install --install-command 'cpanm -n .'
